@extends('admin.layout')
@push('css')
    @include('admin.includes.datatablescss')
@endpush
@section('content')
<div class="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="page-title-box">
                    <h4 class="page-title">
                        All Generated Qr Codes
                    </h4>
                    <div class="pull-right">
                        <a class="btn btn-success" href="{{ route('qrcode.export') }}"><span><i class="mdi mdi-export">
                            </i> Export to Excel</span></a>
                    </div>
                    <div class="clearfix">
                    </div>
                </div>
            </div>
        </div>
        <!-- end row -->
        <div class="row">
            <div class="col-sm-12">
                @include('admin.partials.flash')
                <div class="card-box table-responsive">
                    <table class="table table-striped table-bordered" id="order_table">
                        <thead>
                            <tr>
                                <th>
                                    Reference Number
                                </th>
                                <th>
                                    Generated By
                                </th>
                                <th>
                                    Scanned By
                                </th>
                                <th>
                                    Amount
                                </th>
                                <th>
                                    Created At
                                </th>
                                <th>
                                    Scanned
                                </th>
                                <th>
                                    Scanned On
                                </th>
                                <th>
                                    Action
                                </th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="panel-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content p-0 b-0">
            <div class="panel panel-color panel-primary">
                <div class="panel-heading">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h3 class="panel-title" id="modal_head">Qrcode Details</h3>
                </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="text-center">
                                    <img src="" width="200" height="200" id="modal_qr_path">
                                </div>
                            </div>
                            <div class="col-md-6 col-md-offset-3">
                                <div class="well well-sm mt-10 text-center" id="modal_code"></div>
                            </div>
                            <div class="col-md-12 well well-sm mt-10 text-center" id="scanned_by_div" hidden>
                                <div>QR code scanned by <span class="text-danger" id="scanned_by_name"></span> On <span class="text-danger" id="scanned_by_date"></span></div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Close</button>
                        </div>
                    </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
@endsection
@push('scripts')
<script>
    $(document).ready( function () {
        $('#order_table').DataTable({
            processing: true,
            // oLanguage: {
            //     sProcessing: "<img src='{{ asset('adminassets/assets/images/load.gif') }}'>"
            // },
            serverSide: true,
            ajax: {
            url: "{{ route('qrcode.index') }}",
            },
            columns: [
            {
            data : 'reference_id',
                render : function(data, type, row, meta) {
                    if(data){
                        return data;
                    }
                    else{
                        return 'N/A';
                    }
                }
            },
            {
            data : 'generated_by', //column name
                render : function(generatedBy, type, row, meta) { //generatedBy is relationship
                    if(generatedBy){
                        return generatedBy.name;
                    }
                    else{
                        return 'N/A';
                    }
                }
            },
            {
            data : 'scanned_by', //column name
                render : function(scannedBy, type, row, meta) { //scannedBy is relationship
                    if(scannedBy){
                        return scannedBy.name;
                    }
                    else{
                        return 'N/A';
                    }
                }
            },
            {
            data : 'amount',
                render : function(data, type, row, meta) {
                    if(data){
                        return data+' Points';
                    }
                    else{
                        return 'N/A';
                    }
                }
            },
            {
               data: 'created_at',
               type: 'num',
               render: {
                  _: 'display',
                  sort: 'timestamp'
               }
            },
            {
            data : 'is_scanned',
                render : function(data, type, row, meta) {
                    if(data == 1){
                        data ='<span class="badge badge-success">Scanned</span>';
                    }
                    else{
                        data = '<span class="badge badge-danger">Not Scanned</span>';
                    }
                    return data;
                }
            },
            {
               data: 'scanned_on',
               type: 'num',
               render: {
                  _: 'display',
                  sort: 'timestamp'
               }
            },
            {
                data: 'action',
                name: 'action',
                orderable: false
            }
            ]
        });
    });
</script>
<script>
    $(document).on('click','[data-reference_id]',function() {
        var order = {
            reference_id : $(this).attr('data-reference_id'),
            is_scanned : $(this).attr('data-is_scanned'),
            scanned_on : $(this).attr('data-scanned_on'),
            code : $(this).attr('data-code'),
            qr_code_path : $(this).attr('data-qr_code_path'),
            scanned_by : $(this).attr('data-scanned_by'),
        }
        $("#modal_code").text(order.code);
        $("#modal_qr_path").attr('src',order.qr_code_path);

        if(order.is_scanned == 1){
            $("#scanned_by_div").attr('hidden',false);
            $("#scanned_by_name").text(order.scanned_by);
            $("#scanned_by_date").text(order.scanned_on);
        }
        else{
            $("#scanned_by_div").attr('hidden',true);
        }
        $('#panel-modal').modal('show');
    });
</script>
@include('admin.includes.datatablesjs')
@endpush
