<?php

namespace App\Exports;

use App\GenerateQrCode;
use Illuminate\Support\Facades\Storage;
use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithHeadings;

class QrcodeExport implements FromArray, WithHeadings
{
    public function headings(): array
    {
        return ["Reference Id", "Generated By", "Scanned By", "Amount","Points Earned", "Code","QR Code", "Scanned On", "Created At"];
    }

    public function array(): array
    {
        $qrcodes = GenerateQrCode::all();
        $data = [];
        foreach ($qrcodes as $key => $qrcode) {
            $data[] = [
            'reference_id' => $qrcode->reference_id,
            'generated_by' => $qrcode->generatedBy->name,
            'scanned_by' => (!is_null($qrcode->scanned_by)) ? $qrcode->scannedBy->name : 'NA',
            'amount' => "S$".$qrcode->amount,
            'points' => $qrcode->points,
            'code' => $qrcode->code,
            'qr_code' => url('/').Storage::url($qrcode->qr_path),
            'scanned_on' => (!is_null($qrcode->scanned_on)) ? $qrcode->scanned_on->format('d M Y') : 'NA',
            'created_at' => (!is_null($qrcode->created_at)) ? $qrcode->created_at->format('d M Y') : 'NA',
        ];
        }
        return $data;
    }
}
